version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_PYTHON_SERVICE_URL=http://python-analyzer:8001
      - VITE_RUST_SERVICE_URL=http://rust-converter:8002
    depends_on:
      - python-analyzer
      - rust-converter
    volumes:
      - .:/app
      - /app/node_modules

  python-analyzer:
    build: ./python-wasm
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    volumes:
      - ./python-wasm:/app

  rust-converter:
    build: ./rust-wasm
    ports:
      - "8002:8002"
    environment:
      - RUST_LOG=debug
    volumes:
      - ./rust-wasm:/app

networks:
  default:
    driver: bridge